# Generated by Django 4.0.5 on 2022-06-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0003_question_anthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='anthor',
            new_name='author',
        ),
        migrations.AddField(
            model_name='answer',
            name='authro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
