# Generated by Django 4.0.5 on 2022-06-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_rename_anthor_question_author_answer_authro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='authro',
            new_name='author',
        ),
    ]
